[backdrop]
enabled = true

[bar.default]
background_opacity = 0.7
# border = "secondary"
# border_width = 2
capsule = true
capsule_opacity = 0.4
center = ["clock", "spacer_2"]
end = [
    "tray",
	"notes",
	"wallhaven",
    "ram",
    "recorder",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "control-center",
]
# margin_edge = 12
# margin_ends = 12
padding = 8
# position = "right"
radius = 12
scale = 1.2
start = [
    "media",
]
# thickness = 42


[bar.left]
background_opacity = 0.7
# border = "secondary"
# border_width = 2
capsule = true
capsule_opacity = 0.4
center = ["workspaces"]
# margin_edge = 12
# margin_ends = 12
# padding = 8
position = "left"
# radius = 12
scale = 1.2
# thickness = 42

[location]
auto_locate = true

[osd]
background_opacity = 0.8
position = "top_left"
scale = 1.0

[shell]
avatar_path = "/home/vitor/archdots/assets/profile.jpg"
font_family = "IBM Plex Mono"

[shell.panel]
transparency_mode = "soft"
clipboard_placement = "attached"
control_center_placement = "attached"
launcher_placement = "attached"
session_placement = "attached"
wallpaper_placement = "attached"

[theme]
# custom_palette = "Stylix"
mode = "dark"
# source = "custom"

[wallpaper]
directory = "/home/vitor/archdots/assets/wallpapers"
enabled = true

[widget.control-center]
custom_image_colorize = true
custom_image = "/usr/share/noctalia/assets/images/distros/arch.svg"
# glyph = "cat"

[widget.network]
show_label = false

[widget.ram]
show_label = false

[widget.tray]
drawer = false
hidden = ["blueman"]

[widget.workspaces]
hide_when_empty = true
minimal = false
